package com.test.listdetail.utils;

import com.test.listdetail.R;

public class Constants {

    public static final String[] NAMES = {
            "Jayne",
            "Lyle",
            "Rodrick",
            "Darrin",
            "Jade",
            "Quiana",
            "Tiffani",
            "Elba",
            "Brandi",
            "Ruby",
            "Emogene",
            "Renato",
            "Twila",
            "Rufina",
            "Claretha",
            "Samatha",
            "Tiny",
            "Anneliese",
            "Paulita",
            "Zelda",
            "Donita",
            "Edna",
            "Love",
            "Andres",
            "Kenia",
            "Kaye",
            "Shanel",
            "Kaleigh",
            "Marleen",
            "Rebecka"
    };

    public static final String[] COMPANIES = {
            "Ball Corporation",
            "PNM Resources Inc",
            "NVR Inc",
            "Metaldyne Corporation",
            "Anadarko Petroleum Corporation",
            "Regis Corporation",
            "Lockheed Martin Corporation",
            "SPX Corp",
            "Xilinx Inc",
            "Leggett & Platt Inc.",
            "Pharmacia Corp",
            "Perot Systems Corp",
            "Noble Energy Inc",
            "Ohio Casualty Corp.",
            "General Cable Corporation",
            "Anixter International Inc.",
            "Staples Inc",
            "Wakenhut Corporation",
            "Cincinnati Financial Corp.",
            "Saks Inc",
            "Manor Care Inc.",
            "Viasystems Group Inc",
            "American Axle & Manufacturing Holdings, Inc.",
            "Fairchild Semiconductor International Inc.",
            "The AES Corporation",
            "Energy East Corporation",
            "Barnes & Noble, Inc.",
            "Petco Animal Supplies Inc.",
            "Nicor Inc",
            "WestPoint Stevens Inc"
    };

    public static final int[] IMAGES = {
            R.drawable.builder,
            R.drawable.builder_1,
            R.drawable.businessman,
            R.drawable.captain,
            R.drawable.cashier,
            R.drawable.concierge,
            R.drawable.courier,
            R.drawable.croupier,
            R.drawable.detective,
            R.drawable.diver,
            R.drawable.doctor_1,
            R.drawable.engineer,
            R.drawable.firefighter_1,
            R.drawable.gentleman,
            R.drawable.journalist,
            R.drawable.judge,
            R.drawable.loader,
            R.drawable.maid,
            R.drawable.manager,
            R.drawable.miner,
            R.drawable.nurse,
            R.drawable.scientist,
            R.drawable.sheriff,
            R.drawable.showman,
            R.drawable.stewardess,
            R.drawable.surgeon,
            R.drawable.taxi_driver,
            R.drawable.teacher,
            R.drawable.waiter,
            R.drawable.writer,
    };
}
